# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - lib/firebase/firebase_options.dart

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error

  # TODO: Find a way to run custom_link & dart_code_metrics at the same time
  plugins:
    # - custom_lint
    - dart_code_metrics

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    avoid_positional_boolean_parameters: false
    flutter_style_todos: false
    always_put_required_named_parameters_first: false

# Learn more: https://dcm.dev/docs/individuals/configuration
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - lib/generated_plugin_registrant.dart
    - lib/firebase/firebase_options.dart
  rules:
    - avoid-dynamic
    - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
